server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.229.85:3306/zhenshuxiwen?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: Ljs046330.
    druid:
      test-while-idle: false #solve error log:testWhileIdle is true, validationQuery not set.
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 666666

  redis:
    host: 118.31.229.85
    port: 6379
    timeout: 2000

  mail:
    host: smtp.qq.com
    username: zhenshuxiwen@foxmail.com
    password: cmofrtdtndyhiafd

mybatis:
  type-aliases-package: com.book.novel.module.*.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true #自动转换下划线和驼峰命名